[build]
builder = "nixpacks"

[variables]
NIXPACKS_PKGS = "ffmpeg"
DJANGO_SETTINGS_MODULE = "youtube_downloader.settings"
PYTHONUNBUFFERED = "1"

[deploy]
startCommand = "cd youtube_downloader && gunicorn youtube_downloader.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
protocol = "tcp"
internal_port = "$PORT"
