services:
  # Backend Service
  - type: web
    name: youtube-downloader-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd youtube_downloader && gunicorn youtube_downloader.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: youtube_downloader.settings
      - key: ALLOWED_HOSTS
        value: youtubedownloader-pkcx.onrender.com
      - key: CORS_ORIGIN_WHITELIST
        value: https://youtubedownloader-frontend.onrender.com
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Service
  - type: web
    name: youtube-downloader-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://youtubedownloader-pkcx.onrender.com
